plugins {
    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
    id 'signing'
    id 'java-library'
    id 'maven-publish'
    id 'org.sonarqube' version '6.0.1.5171'
}

sonarqube {
    properties {
        property 'sonar.projectKey', 'dynatrace-oss_index4j'
        property 'sonar.organization', 'dynatrace-oss'
        property 'sonar.host.url', 'https://sonarcloud.io'
    }
}